### PR TITLE
Added the function check_vert_num that ensures that a set does not co…

### PR DESCRIPTION
**Pull request by yonMaor**
…ntain more points than the graph

### CODE REVIEW

**Comment by pmacg** [comment]
Thanks for your contribution! I have a couple of comments:

Firstly, there is a slight misunderstanding in the requirements of this issue. In particular, the input vertex set could be shorter than the number of vertices in the graph, but still contain indices which are out of range. In this case, the clear error message should also be returned. Could you please add the following test case to the `test_graph.py` file and ensure that it passes. Hopefully this will clear up any confusion about the requirements.

```
def test_out_of_range():
    # Create a graph
    graph = sgtl.graph.complete_graph(5)

    # Check the error message when trying to access a vertex which doesn't exist
    with pytest.raises(IndexError, match="Input vertex set includes indices larger than the number of vertices."):
        _ = graph.volume([6])
    with pytest.raises(IndexError, match="Input vertex set includes indices larger than the number of vertices."):
        _ = graph.volume([0, 1, 2, 3, 4, 5])
    with pytest.raises(IndexError, match="Input vertex set includes indices larger than the number of vertices."):
        _ = graph.weight([0, 1, 2], [6])
```

Then, just a couple of minor points:
* The method `check_vert_num` should be renamed `_check_vert_num` since it is an internal method which should not be called by the user and will not appear in the documentation.
* Once the method is updated to address the test-case above, please make sure to update the docstring on the `_check_vert_num` method to accurately reflect what it does.

Please make sure to run the `./check.sh` script to run all of the tests once you have made your changes, then please update this pull request with the new version. Thanks¬

**Comment by pmacg** [comment]
One other thing: please add an entry to the `changelog.rst` file for the change you have made. Please see the [contributing guidelines](https://github.com/pmacg/py-sgtl/blob/main/CONTRIBUTING.md) for more details.

**Comment by yonMaor** [comment]
Just to make up for my lack of knowledge in graph theory: are the vertices on the graph numbered sequentially? 
What I mean is that if a graph has 5 verteces, will these definitely be numbered 0, 1, 2, 3, 4? Or could they be numbered differently?

**Comment by pmacg** [comment]
In this library, a vertex is simply referred to by its index in the adjacency matrix. So yes, you can assume the vertices are numbered `0, 1, 2, 3, 4` as you say.

**Pull request closed without merging**
